### ISSUE TITLE
Add to pi-apps and review changes in pre-release

### ISSUE THREAD

**Issue by pi-dev500** [pi-dev500/MinecraftMicrosoftPILauncher#3]
- [X] Review bugs of pre-release
- [ ] find a way to modify correctly the java interpreter.

**Comment by pi-dev500** [comment]
@Botspot, Can you add this app to pi-apps? Lwjgl libraries are correctly linked and I have resolved conflicts whith old launcher.

**Comment by pi-dev500** [comment]
It works also on my x86_64 computer.

**Comment by Botspot** [comment]
The current issue we're having with ATLauncher is that users may want to run MC versions 12 or below. That that requires using a different Lwjgl folder.

Currently, we're working to make a script that will automatically check for this, and change the .json profiles automatically.

Is your version better? Does it do this automatically?

**Comment by pi-dev500** [comment]
```
This installer configure lwjgl3arm in the
 json for playing 1.13 and newer but It's
 possible to play 1.12 and olders versions
 by replacing 'lwjgl3arm32' by
 'lwjgl2arm32' in section java/minecraft in
 the atlauncher parameters.
The install code is in setupATpi.sh and 
configs files in atconfigs.
```
outdated

**Comment by pi-dev500** [comment]
In the future,I can also create an gui with a menu that switch between 1.12- and 1.13+.

**Comment by pi-dev500** [comment]
@Botspot @mobilegmYT @chunky-milk

**Comment by NoozAbooz** [comment]
We know, Botspot just needs to make modifications to his code. Also, I'm not sure we should add the whole thing, though adding some segments of it might work.

**Comment by Botspot** [comment]
> In the future,I can also create an automatic switcher between 1.12- and 1.13+.

Yes, that right there is the only hindrance to putting it on Pi-Apps. AFAIK.

Right now, using a bash script is pretty complicated and hacky. @pi-dev500 if you know of a cleaner solution, I'd be interested to know.

**Comment by pi-dev500** [comment]
We can ask the ATlauncher developers were is the game launcher and then customize It.

**Comment by pi-dev500** [comment]
@mobilegmYT I think I have an idea to resolve this problem using bash.

**Comment by pi-dev500** [comment]
@Botspot

**Comment by pi-dev500** [comment]
Modifing the java interpreter is probably the only way.

**Comment by NoozAbooz** [comment]
> Modifing the java interpreter is probably the only way.

I mean that would work well too. If you could find a way to do that with bash I can add it in

**Comment by pi-dev500** [comment]
I just need to have the list of all Snapshots before 1.13 ... Done !

**Comment by pi-dev500** [comment]
We just edit the path of the java interpreter to point on a custom bash script that will change JVM argument.

**Comment by pi-dev500** [comment]
@Botspot @mobilegmYT

**Comment by pi-dev500** [comment]
@mobilegmYT @Botspot  I have the script! to try: use pre-release/setupATpi.sh
```
wget -qO- https://raw.githubusercontent.com/pi-dev500/MinecraftMicrosoftPILauncher/main/pre-release/setupATpi.sh | bash
```

**Comment by pi-dev500** [comment]
Use this issue if you encounter a bug. #4

**Comment by pi-dev500** [comment]
For the instant, i am not sur that can workv ATlauncher have some problems whith JVM arguments

**Comment by pi-dev500** [comment]
@mobilegmYT I think there is a problem with if-else-fi and variables in Shell

**Comment by pi-dev500** [comment]
If you can test it in a virtual machine(vdesktop),this will be a good thing.

**Comment by pi-dev500** [comment]
Now you can also clone this repository and run ```make beta```

**Comment by pi-dev500** [comment]
the java interpreter is in tools/java. If you understand the actual bug, comment here3.

**Comment by pi-dev500** [comment]
It works now perfectly, @Botspot @mobilegmYT !

**Comment by pi-dev500** [comment]
There is only the latests Snapshots that don't works (21w*).

**Comment by mobilegmYT** [comment]
> There is only the latests Snapshots that don't works (21w*).

When I tested it with 1.16.5 I got a error.

**Comment by NoozAbooz** [comment]
Looks like you addd some stuff so I'll test it again.
